version: "3"
services:
  pokemon-crawler:
    image: "pokemon-crawler:0.0.1-SNAPSHOT"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      THC_PORT: 8081
      THC_PATH: /actuator/health
      spring.profiles.active: dev-swarm
  pokemon-portal:
    image: "pokemon-portal:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    depends_on:
      - pokemon-crawler
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      spring.profiles.active: dev-swarm