version: "3"
services:
  pokemon-crawler:
    image: "mimosa1997/pokemon-crawler:1.0.9"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 1m
      timeout: 10s
      retries: 10
    environment:
      THC_PORT: 8081
      THC_PATH: /actuator/health
      spring.profiles.active: "production,crawDaily,migrateBattleTeam"
      SECRET_CONFIG_PATH: "file:/run/secrets/pwd"
    secrets:
      - source: pwd_1.0.2
        target: /run/secrets/pwd
  pokemon-portal:
    image: "mimosa1997/pokemon-portal:1.0.8"
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
    depends_on:
      - pokemon-crawler
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 30s
      timeout: 10s
      retries: 6
    environment:
      spring.profiles.active: "production"
      SECRET_CONFIG_PATH: "file:/run/secrets/pwd"
      THC_PATH: /actuator/health
    secrets:
      - source: pwd_1.0.2
        target: /run/secrets/pwd
secrets:
  pwd_1.0.2:
    external: true