spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@host.docker.internal:27017/deep_pokemon_dev_env?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
    redis:
      host: host.docker.internal
      port: 6379
      timeout: 100
  cloud:
    refresh:
      enabled: false
    loadbalancer:
      eager-load:
        clients:
          - pokemon-crawler
    openfeign:
      client:
        config:
          pokemon-crawler:
            url: http://pokemon-crawler:8081
  web:
    cors: "*"
  security:
    user:
      name: mimosa
      password: ${SPRING_USER_PWD:mimosa}
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: ${JKS_KEY}
          keystore:
            location: ${JKS_PATH}
            password: ${JKS_PWD}
management:
  endpoint:
    health:
      show-components: always
  health:
    redis:
      enabled: false

server:
  ssl:
    bundle: web-server

eureka:
  client:
    enabled: false