spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@host.docker.internal:27017/deep_pokemon_dev_env?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
    redis:
      host: redis_pokemon-cache
      port: 6379
      timeout: 100
      connect-timeout: 100
  cloud:
    refresh:
      enabled: false
    loadbalancer:
      eager-load:
        clients:
          - pokemon-crawler
    openfeign:
      client:
        config:
          pokemon-crawler:
            url: http://pokemon-crawler:8081
  web:
    cors: "*"
  security:
    user:
      name: mimosa
      password: ${SPRING_USER_PWD:mimosa}

management:
  endpoint:
    health:
      show-components: when_authorized
  health:
    redis:
      enabled: false

eureka:
  client:
    enabled: false