spring:
    data:
        mongodb:
            uri: mongodb://root:${MONGODB_PWD}@${MONGODB_HOST}:27017/deep_pokemon?authSource=admin&serverSelectionTimeoutMS=3000&connectTimeoutMS=3000
        redis:
            host: redis_pokemon-cache
            port: 6379
            timeout: ${REDIS_TIMEOUT:100}
            connect-timeout: 2000
    cloud:
        refresh:
            enabled: false
        loadbalancer:
            eager-load:
                clients:
                    - pokemon-crawler
        openfeign:
            client:
                config:
                    pokemon-crawler:
                        url: http://pokemon-crawler:8081
    web:
        cors: "*"
    security:
        user:
            name: mimosa
            password: ${SPRING_USER_PWD:mimosa}

management:
    endpoint:
        health:
            show-components: when_authorized
    health:
        redis:
            enabled: false

eureka:
    client:
        enabled: false