spring:
    data:
        mongodb:
            uri: mongodb://mimosa:filter@localhost:27017/?authSource=admin
            database: deep_pokemon_test
        jackson:
        timeZone : GMT+8
    profiles:
#        active: startCraw
logging:
    config: classpath:logback.xml
server:
    tomcat:
        accesslog:
            enabled: true
            directory: /logs/access
