spring:
    data:
        mongodb:
            uri: mongodb://root:${MONGODB_PWD}@101.43.126.226:27017/deep_pokemon?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
        redis:
            host: 101.43.126.226
            port: 6379
            timeout: 100
    cloud:
        refresh:
            enabled: false
        loadbalancer:
            eager-load:
                clients:
                    - pokemon-crawler
        openfeign:
            client:
                config:
                    pokemon-crawler:
                        url: http://pokemon-crawler:8081
    web:
        cors: "*"
    security:
        user:
            name: mimosa
            password: ${SPRING_USER_PWD:mimosa}
    ssl:
        bundle:
            jks:
                web-server:
                    key:
                        alias: ${JKS_KEY}
                    keystore:
                        location: ${JKS_PATH}
                        password: ${JKS_PWD}
server:
    ssl:
        bundle: web-server

management:
    endpoint:
        health:
            show-components: when_authorized
    health:
        redis:
            enabled: false

eureka:
    client:
        enabled: false