spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      database: deep_pokemon_dev_env
    redis:
      host: localhost
      port: 6379
      timeout: 100
  #禁用templates缓存，方便hotswap
  thymeleaf:
    cache: false
  web:
    cors: "*"
  security:
    user:
      name: mimosa
      password: mimosa
management:
  endpoint:
    health:
      show-components: always
  health:
    redis:
      enabled: false

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /logs/access

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://mimosa:mimosa@localhost:8761/eureka/