spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@101.43.126.226:27017/deep_pokemon?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
  cloud:
    refresh:
      enabled: false
eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-components: always

CRAW_BATTLE_POOL_SIZE: 3
ANALYZE_BATTLE_POOL_SIZE: 1
CRAW_PERIOD_MILLISECOND: 100