spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@${MONGODB_HOST}:27017/deep_pokemon?authSource=admin&serverSelectionTimeoutMS=5000&connectTimeoutMS=5000
    redis:
      host: redis_pokemon-cache
      port: 6379
      timeout: 5000
      connect-timeout: 5000
  cloud:
    refresh:
      enabled: false
eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,loggers
  health:
    redis:
      enabled: false

CRAW_BATTLE_POOL_SIZE: 3
ANALYZE_BATTLE_POOL_SIZE: 1
CRAW_PERIOD_MILLISECOND: 100

PROXY_ENABLE: true
SCRAPER_KEY: ${SCRAPER_API_KEY}