spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@host.docker.internal:27017/?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      database: deep_pokemon_dev_env
      authentication-database: admin
  cloud:
    refresh:
      enabled: false

eureka:
  client:
    enabled: false