spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@101.43.126.226:27017/deep_pokemon?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      database: deep_pokemon
      authentication-database: admin
  cloud:
    refresh:
      enabled: false
eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-components: always