spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@localhost:27017/deep_pokemon_dev_env?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      authentication-database: admin
  cloud:
    refresh:
      enabled: false
  profiles:
    active: startCraw,crawDaily
eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-components: always