spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@host.docker.internal:27017/deep_pokemon_dev_env?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      database: deep_pokemon_dev_env
      authentication-database: admin
    redis:
      host: host.docker.internal
      port: 6379
      timeout: 100
      connect-timeout: 50
  cloud:
    refresh:
      enabled: false

eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,loggers
  health:
    redis:
      enabled: false

CRAW_BATTLE_POOL_SIZE: 16
FORK_CRAW_BATTLE_POOL_SIZE: 6
CRAW_PERIOD_MILLISECOND: 300