spring:
  data:
    mongodb:
      uri: mongodb://root:mimosa@localhost:27017/deep_pokemon_dev_env?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
    redis:
      host: localhost
      port: 6379
      timeout: 100
  cloud:
    refresh:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://mimosa:mimosa@localhost:8761/eureka/
management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,loggers

CRAW_BATTLE_POOL_SIZE: 16
ANALYZE_BATTLE_POOL_SIZE: 6
CRAW_PERIOD_MILLISECOND: 1000