spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PWD}@host.docker.internal:27017/deep_pokemon_dev_env?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      database: deep_pokemon_dev_env
      authentication-database: admin
  cloud:
    refresh:
      enabled: false

eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,loggers

CRAW_BATTLE_POOL_SIZE: 16
ANALYZE_BATTLE_POOL_SIZE: 6
CRAW_PERIOD_MILLISECOND: 300